package com.metanit;

public class RomanNumbers {

    public static String getRomanResult(int result) {

        String RomRes = null;
        switch (result) {
            case 1 -> RomRes = "I";
            case 2 -> RomRes = "II";
            case 3 -> RomRes = "III";
            case 4 -> RomRes = "IV";
            case 5 -> RomRes = "V";
            case 6 -> RomRes = "VI";
            case 7 -> RomRes = "VII";
            case 8 -> RomRes = "VIII";
            case 9 -> RomRes = "IX";
            case 10 -> RomRes = "X";
            case 11 -> RomRes = "XI";
            case 12 -> RomRes = "XII";
            case 13 -> RomRes = "XIII";
            case 14 -> RomRes = "XIV";
            case 15 -> RomRes = "XV";
            case 16 -> RomRes = "XVI";
            case 17 -> RomRes = "XVII";
            case 18 -> RomRes = "XVIII";
            case 19 -> RomRes = "XIX";
            case 20 -> RomRes = "XX";
            case 21 -> RomRes = "XXI";
            case 22 -> RomRes = "XXII";
            case 23 -> RomRes = "XXIII";
            case 24 -> RomRes = "XXIV";
            case 25 -> RomRes = "XXV";
            case 26 -> RomRes = "XXVI";
            case 27 -> RomRes = "XXVII";
            case 28 -> RomRes = "XXVIII";
            case 29 -> RomRes = "XXIX";
            case 30 -> RomRes = "XXX";
            case 31 -> RomRes = "XXXI";
            case 32 -> RomRes = "XXXII";
            case 33 -> RomRes = "XXXIII";
            case 34 -> RomRes = "XXXIV";
            case 35 -> RomRes = "XXXV";
            case 36 -> RomRes = "XXXVI";
            case 37 -> RomRes = "XXXVII";
            case 38 -> RomRes = "XXXVIII";
            case 39 -> RomRes = "XXXIX";
            case 40 -> RomRes = "XL";
            case 41 -> RomRes = "XLI";
            case 42 -> RomRes = "XLII";
            case 43 -> RomRes = "XLIII";
            case 44 -> RomRes = "XLIV";
            case 45 -> RomRes = "XLV";
            case 46 -> RomRes = "XLVI";
            case 47 -> RomRes = "XLVII";
            case 48 -> RomRes = "XLVIII";
            case 49 -> RomRes = "XLIX";
            case 50 -> RomRes = "L";
            case 51 -> RomRes = "LI";
            case 52 -> RomRes = "LII";
            case 53 -> RomRes = "LIII";
            case 54 -> RomRes = "LIV";
            case 55 -> RomRes = "LV";
            case 56 -> RomRes = "LVI";
            case 57 -> RomRes = "LVII";
            case 58 -> RomRes = "LVIII";
            case 59 -> RomRes = "LIX";
            case 60 -> RomRes = "LX";
            case 61 -> RomRes = "LXI";
            case 62 -> RomRes = "LXII";
            case 63 -> RomRes = "LXIII";
            case 64 -> RomRes = "LXIV";
            case 65 -> RomRes = "LXV";
            case 66 -> RomRes = "LXVI";
            case 67 -> RomRes = "LXVII";
            case 68 -> RomRes = "LXVIII";
            case 69 -> RomRes = "LXIX";
            case 70 -> RomRes = "LXX";
            case 71 -> RomRes = "LXXI";
            case 72 -> RomRes = "LXXII";
            case 73 -> RomRes = "LXXIII";
            case 74 -> RomRes = "LXXIV";
            case 75 -> RomRes = "LXXV";
            case 76 -> RomRes = "LXXVI";
            case 77 -> RomRes = "LXXVII";
            case 78 -> RomRes = "LXXVIII";
            case 79 -> RomRes = "LXXIX";
            case 80 -> RomRes = "LXXX";
            case 81 -> RomRes = "LXXXI";
            case 82 -> RomRes = "LXXXII";
            case 83 -> RomRes = "LXXXIII";
            case 84 -> RomRes = "LXXXIV";
            case 85 -> RomRes = "LXXXV";
            case 86 -> RomRes = "LXXXVI";
            case 87 -> RomRes = "LXXXVII";
            case 88 -> RomRes = "LXXXVIII";
            case 89 -> RomRes = "LXXXIX";
            case 90 -> RomRes = "XC";
            case 91 -> RomRes = "XCI";
            case 92 -> RomRes = "XCII";
            case 93 -> RomRes = "XCIII";
            case 94 -> RomRes = "XCIV";
            case 95 -> RomRes = "XCV";
            case 96 -> RomRes = "XCVI";
            case 97 -> RomRes = "XCVII";
            case 98 -> RomRes = "XCVIII";
            case 99 -> RomRes = "XCIX";
            case 100 -> RomRes = "C";
        }
        return RomRes;
    }
}
